name: Continuous Integration Build and Unit Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Test
      run: |
        mvn -B clean verify --file pom.xml
        
    # Fixed artifact upload step with current version
    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: target/*.jar
